# Form implementation generated from reading ui file 'ui/mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWin(object):
    def setupUi(self, MainWin):
        MainWin.setObjectName("MainWin")
        MainWin.resize(500, 550)
        MainWin.setMinimumSize(QtCore.QSize(500, 550))
        MainWin.setMaximumSize(QtCore.QSize(500, 550))
        MainWin.setStyleSheet("#MainWin {\n"
"    background-color: #f8f9fa;\n"
"    border: 1px solid #dee2e6;\n"
"}")
        MainWin.setSizeGripEnabled(False)
        MainWin.setModal(False)
        self.listtask = QtWidgets.QListWidget(parent=MainWin)
        self.listtask.setGeometry(QtCore.QRect(10, 100, 291, 431))
        self.listtask.setObjectName("listtask")
        self.label = QtWidgets.QLabel(parent=MainWin)
        self.label.setGeometry(QtCore.QRect(10, 10, 291, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(parent=MainWin)
        self.tableView.setGeometry(QtCore.QRect(10, 60, 291, 31))
        self.tableView.setObjectName("tableView")
        self.radioButton = QtWidgets.QRadioButton(parent=MainWin)
        self.radioButton.setGeometry(QtCore.QRect(10, 30, 291, 20))
        self.radioButton.setObjectName("radioButton")
        self.label_2 = QtWidgets.QLabel(parent=MainWin)
        self.label_2.setGeometry(QtCore.QRect(350, 460, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.addnewtask = QtWidgets.QPushButton(parent=MainWin)
        self.addnewtask.setGeometry(QtCore.QRect(340, 490, 131, 24))
        self.addnewtask.setObjectName("addnewtask")
        self.marktask = QtWidgets.QPushButton(parent=MainWin)
        self.marktask.setGeometry(QtCore.QRect(310, 100, 51, 41))
        self.marktask.setObjectName("marktask")

        self.retranslateUi(MainWin)
        QtCore.QMetaObject.connectSlotsByName(MainWin)

    def retranslateUi(self, MainWin):
        _translate = QtCore.QCoreApplication.translate
        MainWin.setWindowTitle(_translate("MainWin", "To do list"))
        self.label.setText(_translate("MainWin", "Задачи:"))
        self.radioButton.setText(_translate("MainWin", "Показать выполненные"))
        self.label_2.setText(_translate("MainWin", "Новая задача"))
        self.addnewtask.setText(_translate("MainWin", "Добавить"))
        self.marktask.setText(_translate("MainWin", "✓"))
